### ISSUE TITLE
[kernel] Error 2

### ISSUE THREAD

**Issue by normalfaults** [djwillia/solo5#1]
I get the following error when running make kvm

```
solo5@c3cb20265a39:/$ sudo su
root@c3cb20265a39:/# exit   
exit
solo5@c3cb20265a39:/$ sudo su
root@c3cb20265a39:/# cd /home/solo5/
root@c3cb20265a39:/home/solo5# ls
opt  solo5
root@c3cb20265a39:/home/solo5# cd solo5/
root@c3cb20265a39:/home/solo5/solo5# ls
LICENSE   README.md    disk.img  gdb.txt  kernel      kernel.iso   loader
Makefile  config.bash  docker    iso      kernel.cfg  kvm-br.bash  notes.txt
root@c3cb20265a39:/home/solo5/solo5# make kvm
make -C loader
make[1]: Entering directory '/home/solo5/solo5/loader'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/solo5/solo5/loader'
make -C kernel
make[1]: Entering directory '/home/solo5/solo5/kernel'
bash gen_ld.bash > kernel.ld
x86_64-elf-gcc -T kernel.ld -ffreestanding -O2 -nostdlib -lgcc -z max-page-size=0x1000 -static -fno-PIC -o kernel  app_undefined.o ee_printf.o interrupts.o kernel.o lib.o malloc.o mem.o net.o pci.o printk.o serial.o time.o virtio.o kernel_s.o mem_s.o interrupts_s.o -lgcc  
make[1]: x86_64-elf-gcc: Command not found
Makefile:100: recipe for target 'kernel' failed
make[1]: *** [kernel] Error 127
make[1]: Leaving directory '/home/solo5/solo5/kernel'
Makefile:26: recipe for target 'kernel' failed
make: *** [kernel] Error 2
```

**Comment by djwillia** [comment]
It looks like the cross compiler (x86_64-elf-gcc) is not in your PATH.  

That's strange, because it looks like you're running this from one of the Docker images.  Is that correct?  If so, the following line in the Dockerfile should have added the cross compiler directory to your path:

    echo "PATH=/home/solo5/opt/cross/bin:\$PATH" >> ~/.profile

Can you try adding that manually to your path?  E.g.,

    export PATH=/home/solo5/opt/cross/bin:$PATH

**Comment by normalfaults** [comment]
I am running from the docker image.
 ```docker pull djwillia/solo5```
```docker run -d --privileged --name solo5 -t djwillia/solo5```
```docker exec -it solo5 /bin/bash -l```

before taking your steps
```solo5@c3cb20265a39:/$ echo $PATH
/home/solo5/opt/cross/bin:/home/solo5/opt/cross/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin```

after echo
```solo5@c3cb20265a39:/$ echo "PATH=/home/solo5/opt/cross/bin:\$PATH" >> ~/.profile
solo5@c3cb20265a39:/$ echo $PATH
/home/solo5/opt/cross/bin:/home/solo5/opt/cross/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin```
```solo5@c3cb20265a39:/$ export PATH=/home/solo5/opt/cross/bin:$PATH
solo5@c3cb20265a39:/$ echo $PATH
/home/solo5/opt/cross/bin:/home/solo5/opt/cross/bin:/home/solo5/opt/cross/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin```

same error :

```
solo5@c3cb20265a39:/$ echo $PATH
/home/solo5/opt/cross/bin:/home/solo5/opt/cross/bin:/home/solo5/opt/cross/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
solo5@c3cb20265a39:/$ cd ~/solo5/
solo5@c3cb20265a39:~/solo5$ ls
LICENSE    config.bash  gdb.txt  kernel.cfg   loader
Makefile   disk.img     iso      kernel.iso   notes.txt
README.md  docker       kernel   kvm-br.bash
solo5@c3cb20265a39:~/solo5$ make kvm
make -C loader
make[1]: Entering directory '/home/solo5/solo5/loader'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/solo5/solo5/loader'
make -C kernel
make[1]: Entering directory '/home/solo5/solo5/kernel'
bash gen_ld.bash > kernel.ld
x86_64-elf-gcc -T kernel.ld -ffreestanding -O2 -nostdlib -lgcc -z max-page-size=0x1000 -static -fno-PIC -o kernel  app_undefined.o ee_printf.o interrupts.o kernel.o lib.o malloc.o mem.o net.o pci.o printk.o serial.o time.o virtio.o kernel_s.o mem_s.o interrupts_s.o -lgcc  
make[1]: Leaving directory '/home/solo5/solo5/kernel'
xorriso 1.3.2 : RockRidge filesystem manipulator, libburnia project.

sudo kvm -s -nographic -name foo -m 1024 -cdrom kernel.iso -net nic,model=virtio -net tap,ifname=veth0,script=kvm-br.bash -drive file=disk.img,if=virtio -boot d
Could not access KVM kernel module: No such file or directory
failed to initialize KVM: No such file or directory
Makefile:50: recipe for target 'kvm' failed
make: *** [kvm] Error 1
```

**Comment by djwillia** [comment]
Your PATH is ok now (even though it has duplicates) and this is a different error, because x86_64-elf-gcc is now found.  The new issue is that the KVM module is not found.  Can you try (in the container):

    sudo apt-get install qemu-kvm

**Comment by normalfaults** [comment]
looks like its already installed

```solo5@c3cb20265a39:~/solo5$ sudo apt-get install qemu-kvm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
qemu-kvm is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.```

**Comment by djwillia** [comment]
It looks like the KVM module is not installed in your host's Linux kernel.  Try

    lsmod | grep kvm

If you don't see anything you may need to do

    apt-get install kvm

 in the host.  Once you have that module installed,  the error should go away.

**Comment by djwillia** [comment]
One other alternative is to run under QEMU without KVM.  I'm going to close this issue.
