### ISSUE TITLE
Remove dependency on cross compiler

### ISSUE THREAD

**Issue by djwillia** [djwillia/solo5#12]
@mato wrote:
>Why the dependency on a separate cross-compiler? On an x86_64 Linux host, the distribution-provided gcc should do -ffreestanding just fine.

@djwillia wrote:
> I wanted to fully control the build environment and be 100% sure I knew what headers were being included and that no system headers were in there.  I had a "bad experience" with system headers in a kernel in the past.  Will the gcc-related headers (e.g., stdint.h) pull in any other system headers if -ffreestanding is used?  Again, if it's just my own paranoia, then it would be great to not require a cross compiler!

@mato wrote
>Understood. We should be able to get away w/o needing a cross compiler (as
that's what the mirage-xen target already does), however it may not be the
right thing long term. Will know more once I dissect the current build
system.

**Comment by mato** [comment]
This is now fixed as part of the work done and referred to in #10. @djwillia Can you close the issue?
