### ISSUE TITLE
Timekeeping enhancements

### ISSUE THREAD

**Issue by mato** [djwillia/solo5#13]
The current timekeeping code could be improved. I suggest using the code I wrote for rumprun ([clock.c](https://github.com/rumpkernel/rumprun/blob/master/platform/hw/arch/x86/clock.c), [hypervisor.c](https://github.com/rumpkernel/rumprun/blob/master/platform/hw/arch/x86/hypervisor.c)) for inspiration and/or re-using as much of it as possible. The following cases should be handled (in my rough order of subjective importance and ease of implementation):

1. ukvm hypercall for sleep, KVM pvclock for monotonic and wall time (Solo5 on _ukvm_ target).
2. PIT for sleep, KVM pvclock for monotonic and wall time (Solo5 on _KVM/QEMU_ target).
3. PIT for sleep, TSC-based clock for monotonic time, RTC-based clock for wall time (Solo5 on _plain QEMU_ target).

The rumprun code handles cases 2 and 3, case 1 is a trivial modification of case 2.
This would also let us remove the "clock speed detection" hack from ukvm (see #9).

**Comment by ricarkol** [comment]
Exporting these with the correct implementation now:

```
/* Time */
uint64_t solo5_clock_monotonic(void);
uint64_t solo5_clock_wall(void);

/* Sched related functions */
void solo5_cpu_block(uint64_t);
```

Didn't add sleep(), and added solo5_cpu_block instead, as the real sleep should be implemented by the scheduler on top. For example, mirageos will use this function to implement block_domain().
