### ISSUE TITLE
solo5-kernel-ukvm and solo5-kernel-virtio dependencies

### ISSUE THREAD

**Issue by djwillia** [djwillia/solo5#18]
At the moment, the OPAM dependencies of `mirage-solo5` include both solo5-kernel-ukvm and solo5-kernel-virtio, even though it will only ever be linked against one.

**Comment by mato** [comment]
This has been fixed by the migration to ocaml-freestanding which uses depopts on solo5-kernel-ukvm and solo5-kernel-virtio. While not an ideal way to express the dependency it does solve the problem for now, so I think we can close this.
