### ISSUE TITLE
Built-in multiboot support (was "remove loader")

### ISSUE THREAD

**Issue by djwillia** [djwillia/solo5#20]
The version of Solo5 that runs on QEMU as an ISO currently has a complex loading process, with a 32-bit loader that sets up a lot of system state before jumping to 64-bit.  It would be much cleaner to have a multiboot-compliant 64-bit kernel (ELF) and start that directly with QEMU without needing an ISO.  However, the 64-bit piece currently is not multiboot compliant because the 32-bit loader is doing too much, so it will require a bit of work.

**Comment by hannesm** [comment]
(not sure whether this is the right issue, but the [bhyve](http://bhyve.org/) ([wiki](https://wiki.freebsd.org/bhyve)) boot story is either native FreeBSD kernel, or they ship a [modified grub](https://github.com/grehan-freebsd/grub2-bhyve) for booting other operating systems (see [freshports](https://www.freshports.org/sysutils/grub2-bhyve/)).

Thus, bhyve is multiboot capable, and would be great to get solo5 there (I'd so use it on a daily basis as DNS resolver etc.)!  I'm happy to help&test if you need me.

**Comment by mato** [comment]
@hannesm Thanks for the info re bhyve, will ping you when it's ready to test.
