### ISSUE TITLE
MAC address is hardcoded

### ISSUE THREAD

**Issue by ricarkol** [djwillia/solo5#38]
The MAC address (only one NIC is supported at the moment) is hardcoded here: https://github.com/djwillia/solo5/blob/c98550bbf154d23e8e72e332b26ef3bd9db25e80/ukvm/ukvm.c#L784
And the networking setup script is binding this hardcoded MAC with a hardcoded IP 10.0.0.2 here:
https://github.com/djwillia/solo5/blob/b2149527f0f31f95bcfc1c18bb306aa054cdddc4/solo5-config-net.bash#L18

**Comment by mato** [comment]
As a first step we can just generate a random locally-administered MAC address using /dev/urandom.
