### ISSUE TITLE
ukvm-mirage: Immediate VCPU exit with exit_reason=0x8

### ISSUE THREAD

**Issue by mato** [djwillia/solo5#6]
When running the `config_console` example from the `ukvm-mirage` branch, using the provided Docker container to build, ukvm exits immediately from `vcpu_loop()` with `run->exit_reason` set to `8`. This corresponds to `KVM_EXIT_SHUTDOWN` and is triggered on a triple fault of the VCPU.

Calling `get_and_dump_sregs(vcpufd)` before entering `vcpu_loop()` produces the following dump:
````
 cr0: 00000000e0000011   cr2: 0000000000000000   cr3: 0000000000009000
 cr4: 0000000000000020   cr8: 0000000000000000

 Segment registers:
 ------------------
 register  selector  base              limit     type  p dpl db s l g avl
 cs        0008      0000000000000000  000fffff  0b    1 0   0  1 1 1 0
 ss        0010      0000000000000000  000fffff  03    1 0   1  1 0 1 0
 ds        0010      0000000000000000  000fffff  03    1 0   1  1 0 1 0
 es        0010      0000000000000000  000fffff  03    1 0   1  1 0 1 0
 fs        0010      0000000000000000  000fffff  03    1 0   1  1 0 1 0
 gs        0010      0000000000000000  000fffff  03    1 0   1  1 0 1 0
 tr        0018      0000000000002000  00000067  0b    1 0   0  0 0 0 0
 ldt       0000      0000000000000000  0000ffff  02    1 0   0  0 0 0 0
 gdt                 0000000000000500  00000027
 idt                 0000000000001000  00000fff
````
This seems fine. I've also verified with `gdb` that the page table setup looks OK. Further, adding some debug code to call and dump `KVM_GET_REGS` after the `KVM_RUN` ioctl returns shows that the VCPU does not get past the first instruction in `kernel_main()`.

My system is an Intel Sandy Bridge laptop, with an Intel Core i5-2540M CPU. VT-x and VT-d (IOMMU) are both enabled. I'm running Linux kernel version 4.1.20.

**Comment by mato** [comment]
Trying the workaround suggested by @ricarkol to load `kvm_intel` with `ept=0` does not work either. The only difference is I get a warning in the kernel log about `KVM_SET_TSS_ADDR` not being called. Enabling the commented out call in `ukvm.c` and rebuilding does not change anything either.

FWIW, [this thread](https://lwn.net/Articles/658863/) provides some explanation of `KVM_SET_TSS_ADDR`, if I'm reading it right it only matters for KVM guests running in real (well, vm86) mode?

**Comment by mato** [comment]
A further data point: I tried rebooting with the stock Debian jessie kernel (3.16.0) and get exactly the same result, so it looks like we can rule out any KVM interface change (@djwillia mentioned he's also on 3.16).

**Comment by djwillia** [comment]
Yes, the system registers match what I have on my working setup.  I have not yet been able to reproduce the problem.  The working setup is running an Intel Xeon X5675 with VT-x enabled and Linux kernel version 3.16.0.  Not sure if it's relevant or not, but how do you check VT-d status?

What about how the module is loaded?  Here's some info about the kvm module in the working setup:

    $ cat /proc/modules |grep kvm
    kvm_intel 143590 0 - Live 0x0000000000000000
    kvm 452043 1 kvm_intel, Live 0x0000000000000000

    $ for f in /sys/module/kvm/parameters/*; do echo -n "`basename $f` "; cat $f; done
    allow_unsafe_assigned_interrupts N
    ignore_msrs N
    min_timer_period_us 500
    tsc_tolerance_ppm 250

    $ for f in /sys/module/kvm_intel/parameters/*; do echo -n "`basename $f` "; cat $f; done
    emulate_invalid_guest_state Y
    enable_apicv N
    enable_shadow_vmcs N
    ept Y
    eptad N
    fasteoi Y
    flexpriority Y
    nested Y
    ple_gap 128
    ple_window 4096
    unrestricted_guest Y
    vmm_exclusive Y
    vpid Y

Any hints in there?

**Comment by djwillia** [comment]
Oops didn't mean to close!

**Comment by mato** [comment]
VT-d is normally a BIOS setting. If your `dmesg` says anything about an `IOMMU` then that usually means its enabled. 

KVM parameters on my system:
````
$ cat /proc/modules |grep kvm
kvm_intel 147456 0 - Live 0xffffffffa0915000
kvm 417792 1 kvm_intel, Live 0xffffffffa06e5000
$ for f in /sys/module/kvm/parameters/*; do echo -n "`basename $f` "; cat $f; done
allow_unsafe_assigned_interrupts N
halt_poll_ns 0
ignore_msrs N
lapic_timer_advance_ns 0
min_timer_period_us 500
tsc_tolerance_ppm 250
$ for f in /sys/module/kvm_intel/parameters/*; do echo -n "`basename $f` "; cat $f; done
emulate_invalid_guest_state Y
enable_apicv N
enable_shadow_vmcs N
ept Y
eptad N
fasteoi Y
flexpriority Y
nested N
ple_gap 0
ple_window 4096
ple_window_grow 2
ple_window_max 1073741823
ple_window_shrink 0
pml N
unrestricted_guest Y
vmm_exclusive Y
vpid Y
````
Nothing jumps out there. I've been testing with `nested` both enabled and disabled. The PLE stuff shouldn't matter.

**Comment by ricarkol** [comment]
Some more info. I'm running on an intel i5, these are teh results of these combinations:
kernel 4.3.3-1 with ept=ON        fail (exit_reason = 0x8)
kernel 4.3.3-1 with ept=OFF      fail (exit_reason = 0x8)
kernel 3.10.94 with ept=ON     fail (exit_reason = 0x8)
kernel 3.10.94 with ept=ON     pass

**Comment by mato** [comment]
I just tried 3.16.0 with ept=OFF and that also fails.

**Comment by mato** [comment]
Aha! One *successful* data point: I copied the binaries to a rather old and different machine (2x AMD Opteron 8356, kernel 3.2.0) and it works. So there's definitely something with my hardware that's triggering the problem.

**Comment by mato** [comment]
And yet another one: Ubuntu 15.10 (kernel 4.2.0, AMD Opteron 3350 HE). Works. What's notable is that this is a much newer kernel, so it looks like it's something specific to my laptop that's triggering the problem.

**Comment by djwillia** [comment]
Ok, I now have a machine that is also failing in the same way (kernel 3.16, Intel Xeon E5420).  I've run "kvmtest" successfully on that machine, so I'm going to look into what the difference is, which seems promising.  "kvmtest" is a really simple test of the KVM interface that you can find at http://lwn.net/Articles/658512/

**Comment by ricarkol** [comment]
Couple more datapoints with lkvm (kvmtool) with clear-container patches (https://github.com/clearlinux/kvmtool.gitwith branch=clear-patches). Could reproduce the same problem:

./lkvm run /usr/src/bzImage -d disk.img  # this is the regular path: vcpu starts in single mode. This works (in my laptop) for kernel 3.10 and kernel 4.3.

./lkvm run -k /usr/src/vmlinux -d disk.img # this is similar to what ukvm does: vcpu starts already in protected mode. This only works for kernel 3.10.

**Comment by mato** [comment]
I've tested another machine, which works: 2015 vintage, Intel NUC w/ Core i7-5557U. Running freshly updated Debian testing (stretch), kernel 4.4.0 (4.4.6-1).

**Comment by mato** [comment]
Got it: My laptop's CPU does not support 1GB pages (no `pdpe1g` present in `/proc/cpuinfo`, confirmed with `x86info -a`). The machines where it works for me do support it. See also Intel SDM vol. 3A, section 4.1.4 "Enumeration of Paging Features by CPUID".

**Comment by mato** [comment]
I've addressed this in #8 by switching to 2MB pages for the guest which makes things work on my machine. Intel SDM 4.1.4 (referenced above) implies that if long mode (called IA-32e in their manuals) is supported then 2MB pages must also be supported, so this should work on all x86-64 processors.
@djwillia Please test and merge if you're happy with it. @ricarkol This should work on the kernel/machine combinations that were previously failing for you. If not, then your issue with VMENTRY is different to mine.

**Comment by djwillia** [comment]
@mato Great job, that was fixed the issue on the machine I found that was failing too.  It seems like we may need to do a bit of hardware discovery.  I think it should be done in ukvm rather than in the guest.  CPU speed is a place that some "discovery" is happening, but it is a horrible hack:
https://github.com/djwillia/solo5/blob/ukvm-mirage/ukvm/ukvm.c#L687
It might make sense to have a little configuration script which figures out what we need to know and generates a header or something for ukvm.c   What do you think?

**Comment by mato** [comment]
Let's discuss feature discovery in #9 so that we don't pollute this issue. We can close this one when @ricarkol confirms my change in #8 solves the problem for him.

**Comment by ricarkol** [comment]
it works!

            |      ___|  
  __|  _ \  |  _ \ __ \  
\__ \ (   | | (   |  ) | 
____/\___/ _|\___/____/  
Solo5: new bindings
hello
world
hello
world
hello
world
hello
world
Kernel done. 
Goodbye!
KVM_EXIT_HLT
0:04.75 elapsed
solo5@8dc1ae7fe74e:~/solo5$ uname -a
Linux 8dc1ae7fe74e **4.3.3-1.el6.elrepo.x86_64** #1 SMP Tue Dec 15 13:13:15 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ricarkol** [comment]
Closing
